check50:
  files: &check50_files
    - !exclude "*"
    - !include "grades0.c"
    - !include "grades1.c"
    - !include "powers.c"
    - !include "while.c"
    - !include "*.txt"

submit50:
  files: *check50_files
